import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/Link'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Funções API Gemini</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.headerIndex}>
          <ul>
            <li>
              <Link href="/textToText/">Text To Text</Link>
            </li>
            <li>
              <Link href="/textToImage/">Text To Image</Link>
            </li>
            <li>
              <Link href="/imageToText/">Image To Text</Link>
            </li>
            {/** 
             * 
            <li>
              <Link href="/imageToImage/">Image To Image</Link>
            </li>
            <li>
              <Link href="/textToAudio/">Text To Audio</Link>
            </li>
            */}
            <li>
              <Link href="/audioToText/">Audio To Text</Link>
            </li>
            {/**
             * <li>
                  <Link href="/textToVideo/">Text To Video</Link>
               </li>
             */}
            <li>
              <Link href="/videoToText/">Video To Text</Link>
            </li>
            <li>
              <Link href="/pdfToText/">PDF To Text</Link>
            </li>
          </ul>
        </header>
        {/**<section className={styles.sectionCorpo}>
          <div className={styles.modelos}>
            <Image src="/gemini.webp" alt="Gemini Logo" width={200} height={200} />
          </div>
          <div className={styles.modelos}>
            <Image src="/openai.png" alt="Openai Logo" width={200} height={200} />
          </div>
          <div className={styles.modelos}>
            <Image src="/hugging.jpg" alt="Huggingface Logo" width={200} height={200} />
          </div>

        </section> */}
      </main>

      <footer className={styles.footer}>
        <h2>Gemini</h2>
      </footer>
    </div>
  )
}
