import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/Link'
import styles from '../styles/Home.module.css'

export default function TextToVideo() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Funções API Gemini</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <header className={styles.header}>
                    <ul>
                        <li>
                            <h1><Link href="./">Index</Link></h1>
                        </li>
                    </ul>
                </header>
            </main>

        </div>
    )
}
